### ISSUE TITLE
Contact Posting/Manager Views

### ISSUE THREAD

**Issue by JoeWrightNC** [schmitty890/homestead#149]
@catchbb14 @schmitty890 @tommyngre  

For contact, I figure we can either use formspree (https://formspree.io/, great to use in your portfolio if it is new to you) to make our form post to email, or what I want to do is make it so the contact form writes to a database for holding messages.  The thought there is we would then add a manager account with an added nav tab for management.  The manager portal would have at least two functionalities as I see it:  Managing Messages (put them in different categories and delete), and a view for posting dues to different users.  I'd then add a tab to the current account page to view dues, that would populate out of that same db.  The user db would populate a selector for the manager when assigning dues.

Also worth noting, we can easily add a column for account level to the user model, and then use the handlebars process we've already implemented to check logged in/out to also check account level.  Good method Jason.

Let me know your thoughts, if everyone is on board I'll make all the functionalities happen.

**Comment by schmitty890** [comment]
sounds good. do it to it!

**Comment by JoeWrightNC** [comment]
doing it
