### ISSUE TITLE
incorporate css partials

### ISSUE THREAD

**Issue by tommyngre** [schmitty890/homestead#27]
break down template css into these partials

1. Shared vars
2. Classes
3. Element styling
4. Forms
5. Universal classes
6. Responsive

**Comment by schmitty890** [comment]
@tommyngre i have read up on some sass best practices over the weekend, and have read it is considered good practice to begin the filename of any partial with an underscore as shown in this screenshot. apparently this is known to make it more clear to other devs, as if the file has _ in front of it, it indicates its a partial.
 
<img width="221" alt="screen shot 2018-06-05 at 10 44 37 pm" src="https://user-images.githubusercontent.com/16051859/41012958-1d4fde0e-6912-11e8-8541-2c88ee1c4719.png">

**Comment by tommyngre** [comment]
closing. initial implementation handled here:
https://github.com/schmitty890/homestead/pull/60
