### ISSUE TITLE
Create faq page

### ISSUE THREAD

**Issue by schmitty890** [schmitty890/homestead#49]
Create an faq html route so when we hit it we are navigate to oursite/faq we get a list of frequently asked questions.

The faq page can read in a static json file we write and host on our site to populate the questions and answers.

html-route: `/faq`

the json data creation of this page is story https://github.com/schmitty890/homestead/issues/50

**Comment by catchbb14** [comment]
Route has been added in html-routes.js.

We will need to populate with questions as we get closer to a more complete prototype.
